# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-19 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_location_captain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=255)),
                ('main_framework', models.CharField(max_length=255)),
                ('is_first_stack', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='stacks_offered',
            field=models.ManyToManyField(related_name='available_locations', to='location.Stack'),
        ),
    ]
